apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: kubernetes-test
spec:
  selector:
    matchLabels:
      app: kubernetes-test
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: kubernetes-test
    spec:
      containers:
        - name: kubernetes-test
          image: jishnuvs/kubernetes-test.jar:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster