package com.camel.model;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.05.28 at 05:05:12 PM IST
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="payload1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="payload2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="payload3" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "payload1",
        "payload2",
        "payload3"
})
@XmlRootElement(name = "bulkmessage")
public class Bulkmessage {

    @XmlElement(required = true)
    protected String payload1;
    @XmlElement(required = true)
    protected String payload2;
    @XmlElement(required = true)
    protected String payload3;

    /**
     * Gets the value of the payload1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPayload1() {
        return payload1;
    }

    /**
     * Sets the value of the payload1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPayload1(String value) {
        this.payload1 = value;
    }

    /**
     * Gets the value of the payload2 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPayload2() {
        return payload2;
    }

    /**
     * Sets the value of the payload2 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPayload2(String value) {
        this.payload2 = value;
    }

    /**
     * Gets the value of the payload3 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPayload3() {
        return payload3;
    }

    /**
     * Sets the value of the payload3 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPayload3(String value) {
        this.payload3 = value;
    }

}
